export const LOGIN = 'APPLICATION/LOGIN';
export const LOGGED_USER = 'APPLICATION/LOGGED_USER';
export const LOGOUT = 'APPLICATION/LOGOUT';

export const ALBUMS_FETCH = 'ALBUMS/FETCH';
export const ALBUMS_FETCH_SUCCESS = 'ALBUMS/FETCH_SUCCESS';
export const ALBUMS_FETCH_FAILURE = 'ALBUMS/FETCH_FAILURE';
export const SORT_ALBUMS = 'ALBUMS/SORT_ALBUMS';

export const POSTS_FETCH = 'POSTS/FETCH';
export const POSTS_FETCH_SUCCESS = 'POSTS/FETCH_SUCCESS';
export const POSTS_FETCH_FAILURE = 'POSTS/FETCH_FAILURE';
export const SORT_POSTS = 'POSTS/SORT_ALBUMS';
